### ISSUE TITLE
npm package publish workflow doesn't work

### ISSUE THREAD

**Issue by FilledStacks** [FilledStacks/firebase-backend#4]
When pushing a new version of the package with updated version code on the main branch the workflow to publish the package runs but it doesn't actually upload the package. 

I still have to run `npm publish` locally to push the updated version

**Comment by llewellyncollins** [comment]
Could be because the version in the package-lock does not match the git tags. I will make another PR with an attempted fix. Like I said in the PR it is not easy to debug without being logged into the correct npm account as I cannot test npm publish

**Comment by llewellyncollins** [comment]
@FilledStacks can you please publish that locally  and send the URL to the package

**Comment by FilledStacks** [comment]
@llewellyncollins I totally understand. The package is published [here](https://www.npmjs.com/package/firebase-backend) I just wanted to log the bug so I can look at it when I get time. You've done a lot to help already. It's crazy how little time is available to write code when you code for a living. 

I'd appreciate a look at it, but it's not that critical. I can just run publish locally for now until you get time to check it out.

**Comment by mxttwoods** [comment]
@FilledStacks I think you need something like this but with the npm registry and auth token. 

Although I keep all my npm publishing manually. 

```yaml
name: Publish Package to Github

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    env:
      working-directory: ./package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn install
        working-directory: ${{env.working-directory}}
      - name: Build
        run: yarn build
        working-directory: ${{env.working-directory}}
      - name: Test
        run: yarn test
        working-directory: ${{env.working-directory}}
      - name: Publish
        run: yarn publish
        working-directory: ${{env.working-directory}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
